<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>4 Gráficos para variables cualitativas | Gráficos con R</title>
  <meta name="description" content="Libro de apoyo para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="4 Gráficos para variables cualitativas | Gráficos con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="images/cover.png" />
  <meta property="og:description" content="Libro de apoyo para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="github-repo" content="fhernanb/Graficos-con-R" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="4 Gráficos para variables cualitativas | Gráficos con R" />
  
  <meta name="twitter:description" content="Libro de apoyo para los estudiantes de la Escuela de Estadística de la Universidad Nacional de Colombia." />
  <meta name="twitter:image" content="images/cover.png" />

<meta name="author" content="Freddy Hernández">
<meta name="author" content="Juan Carlos Correa">


<meta name="date" content="2019-07-04">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="dos-cuanti.html">
<link rel="next" href="funcion-par.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {  }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Gráficos con R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Bienvenido</a><ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#estructura-del-libro"><i class="fa fa-check"></i>Estructura del libro</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#software-y-convenciones"><i class="fa fa-check"></i>Software y convenciones</a></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#bloques-informativos"><i class="fa fa-check"></i>Bloques informativos</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="sobre-los-autores.html"><a href="sobre-los-autores.html"><i class="fa fa-check"></i>Sobre los autores</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a></li>
<li class="chapter" data-level="2" data-path="una-cuanti.html"><a href="una-cuanti.html"><i class="fa fa-check"></i><b>2</b> Gráficos para una variable cuantitativa</a><ul>
<li class="chapter" data-level="2.1" data-path="una-cuanti.html"><a href="una-cuanti.html#funcion-stem"><i class="fa fa-check"></i><b>2.1</b> Función <code>stem</code>  </a><ul>
<li class="chapter" data-level="" data-path="una-cuanti.html"><a href="una-cuanti.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="una-cuanti.html"><a href="una-cuanti.html#funcion-boxplot"><i class="fa fa-check"></i><b>2.2</b> Función <code>boxplot</code> </a><ul>
<li class="chapter" data-level="" data-path="una-cuanti.html"><a href="una-cuanti.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="una-cuanti.html"><a href="una-cuanti.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="una-cuanti.html"><a href="una-cuanti.html#funcion-hist"><i class="fa fa-check"></i><b>2.3</b> Función <code>hist</code></a><ul>
<li class="chapter" data-level="" data-path="una-cuanti.html"><a href="una-cuanti.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="una-cuanti.html"><a href="una-cuanti.html#funcion-qqnorm-y-qqplot"><i class="fa fa-check"></i><b>2.4</b> Función <code>qqnorm</code> y <code>qqplot</code>  </a><ul>
<li class="chapter" data-level="" data-path="una-cuanti.html"><a href="una-cuanti.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="una-cuanti.html"><a href="una-cuanti.html#ejemplo-5"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="una-cuanti.html"><a href="una-cuanti.html#funcion-density"><i class="fa fa-check"></i><b>2.5</b> Función <code>density</code>  </a><ul>
<li class="chapter" data-level="" data-path="una-cuanti.html"><a href="una-cuanti.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="una-cuanti.html"><a href="una-cuanti.html#ejemplo-7"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="una-cuanti.html"><a href="una-cuanti.html#ejemplo-8"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="dos-cuanti.html"><a href="dos-cuanti.html"><i class="fa fa-check"></i><b>3</b> Gráficos para varias variables cuantitativas</a><ul>
<li class="chapter" data-level="3.1" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-plot"><i class="fa fa-check"></i><b>3.1</b> Función <code>plot</code>  </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-9"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-10"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-sunflowerplot"><i class="fa fa-check"></i><b>3.2</b> Función <code>sunflowerplot</code> </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-11"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-12"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-symbols"><i class="fa fa-check"></i><b>3.3</b> Función <code>symbols</code> </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-13"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-pairs"><i class="fa fa-check"></i><b>3.4</b> Función <code>pairs</code> </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-14"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-15"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-16"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-17"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-18"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-persp"><i class="fa fa-check"></i><b>3.5</b> Función <code>persp</code> </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-19"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-20"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-contour"><i class="fa fa-check"></i><b>3.6</b> Función <code>contour</code>  </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-21"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-filled.contour"><i class="fa fa-check"></i><b>3.7</b> Función <code>filled.contour</code>  </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-22"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-23"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.8" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-image"><i class="fa fa-check"></i><b>3.8</b> Función <code>image</code> </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-24"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.9" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-kde2d"><i class="fa fa-check"></i><b>3.9</b> Función <code>kde2d</code>  </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-25"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.10" data-path="dos-cuanti.html"><a href="dos-cuanti.html#funcion-interaction.plot"><i class="fa fa-check"></i><b>3.10</b> Función <code>interaction.plot</code>  </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-26"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="3.11" data-path="dos-cuanti.html"><a href="dos-cuanti.html#grafico-de-espagueti"><i class="fa fa-check"></i><b>3.11</b> Gráfico de espagueti </a><ul>
<li class="chapter" data-level="" data-path="dos-cuanti.html"><a href="dos-cuanti.html#ejemplo-27"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html"><i class="fa fa-check"></i><b>4</b> Gráficos para variables cualitativas</a><ul>
<li class="chapter" data-level="4.1" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html#funcion-barplot"><i class="fa fa-check"></i><b>4.1</b> Función <code>barplot</code>  </a><ul>
<li class="chapter" data-level="" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html#ejemplo-28"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html#ejemplo-29"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html#funcion-pie"><i class="fa fa-check"></i><b>4.2</b> Función <code>pie</code>  </a><ul>
<li class="chapter" data-level="" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html#ejemplo-30"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html#funcion-dotchart"><i class="fa fa-check"></i><b>4.3</b> Función <code>dotchart</code>  </a><ul>
<li class="chapter" data-level="" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html#ejemplo-31"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html#ejemplo-32"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="graficos-para-variables-cualitativas.html"><a href="graficos-para-variables-cualitativas.html#ejercicios"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="funcion-par.html"><a href="funcion-par.html"><i class="fa fa-check"></i><b>5</b> Función <code>par</code></a><ul>
<li class="chapter" data-level="5.1" data-path="funcion-par.html"><a href="funcion-par.html#parametro-ann"><i class="fa fa-check"></i><b>5.1</b> Parámetro <code>ann</code>  </a><ul>
<li class="chapter" data-level="" data-path="funcion-par.html"><a href="funcion-par.html#ejemplo-33"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="funcion-par.html"><a href="funcion-par.html#parametro-adj"><i class="fa fa-check"></i><b>5.2</b> Parámetro <code>adj</code>  </a><ul>
<li class="chapter" data-level="" data-path="funcion-par.html"><a href="funcion-par.html#ejemplo-34"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="funcion-par.html"><a href="funcion-par.html#parametro-bg"><i class="fa fa-check"></i><b>5.3</b> Parámetro <code>bg</code>  </a><ul>
<li class="chapter" data-level="" data-path="funcion-par.html"><a href="funcion-par.html#ejemplo-35"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="funcion-par.html"><a href="funcion-par.html#parametro-mfrow"><i class="fa fa-check"></i><b>5.4</b> Parámetro <code>mfrow</code>  </a><ul>
<li class="chapter" data-level="" data-path="funcion-par.html"><a href="funcion-par.html#ejemplo-36"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.5" data-path="funcion-par.html"><a href="funcion-par.html#parametro-bty"><i class="fa fa-check"></i><b>5.5</b> Parámetro <code>bty</code>  </a><ul>
<li class="chapter" data-level="" data-path="funcion-par.html"><a href="funcion-par.html#ejemplo-37"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="funcion-par.html"><a href="funcion-par.html#parametro-cex"><i class="fa fa-check"></i><b>5.6</b> Parámetro <code>cex</code>  </a><ul>
<li class="chapter" data-level="" data-path="funcion-par.html"><a href="funcion-par.html#ejemplo-38"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.7" data-path="funcion-par.html"><a href="funcion-par.html#parametros-cex.axis-cex.lab-cex.main-y-cex.sub"><i class="fa fa-check"></i><b>5.7</b> Parámetros <code>cex.axis</code>, <code>cex.lab</code>, <code>cex.main</code> y <code>cex.sub</code>    </a><ul>
<li class="chapter" data-level="" data-path="funcion-par.html"><a href="funcion-par.html#ejemplo-39"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="funcion-par.html"><a href="funcion-par.html#parametro-col-col.axis-col.lab-col.main-y-col.sub"><i class="fa fa-check"></i><b>5.8</b> Parámetro <code>col</code>, <code>col.axis</code>, <code>col.lab</code>, <code>col.main</code> y <code>col.sub</code>  </a><ul>
<li class="chapter" data-level="" data-path="funcion-par.html"><a href="funcion-par.html#ejemplo-40"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html"><i class="fa fa-check"></i><b>6</b> Funciones auxiliares</a><ul>
<li class="chapter" data-level="6.1" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#funcion-segments"><i class="fa fa-check"></i><b>6.1</b> Función <code>segments</code>  </a></li>
<li class="chapter" data-level="6.2" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#funcion-rect"><i class="fa fa-check"></i><b>6.2</b> Función <code>rect</code>  </a></li>
<li class="chapter" data-level="6.3" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#funcion-polygon"><i class="fa fa-check"></i><b>6.3</b> Función <code>polygon</code>  </a></li>
<li class="chapter" data-level="6.4" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#funcion-abline"><i class="fa fa-check"></i><b>6.4</b> Función <code>abline</code> </a></li>
<li class="chapter" data-level="6.5" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#para-dibujar-un-circulo"><i class="fa fa-check"></i><b>6.5</b> Para dibujar un círculo </a></li>
<li class="chapter" data-level="6.6" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#funcion-arrows"><i class="fa fa-check"></i><b>6.6</b> Función <code>arrows</code>  </a></li>
<li class="chapter" data-level="6.7" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#funcion-grid"><i class="fa fa-check"></i><b>6.7</b> Función <code>grid</code>  </a></li>
<li class="chapter" data-level="6.8" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#funcion-points"><i class="fa fa-check"></i><b>6.8</b> Función <code>points</code>  </a></li>
<li class="chapter" data-level="6.9" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#funcion-curve"><i class="fa fa-check"></i><b>6.9</b> Función <code>curve</code>  </a><ul>
<li class="chapter" data-level="" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#ejemplo-41"><i class="fa fa-check"></i>Ejemplo</a></li>
<li class="chapter" data-level="" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#ejemplo-42"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="funciones-auxiliares.html"><a href="funciones-auxiliares.html#ejercicios-1"><i class="fa fa-check"></i>EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html"><i class="fa fa-check"></i><b>7</b> Respuestas a preguntas frecuentes</a><ul>
<li class="chapter" data-level="7.1" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html#como-crear-un-grafico-vacio"><i class="fa fa-check"></i><b>7.1</b> ¿Cómo crear un gráfico vacío? </a></li>
<li class="chapter" data-level="7.2" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html#como-personalizar-los-valores-a-mostrar-en-los-ejes"><i class="fa fa-check"></i><b>7.2</b> ¿Cómo personalizar los valores a mostrar en los ejes?</a></li>
<li class="chapter" data-level="7.3" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html#como-dibujar-varios-qqplot-en-una-misma-figura"><i class="fa fa-check"></i><b>7.3</b> ¿Cómo dibujar varios QQplot en una misma figura?</a></li>
<li class="chapter" data-level="7.4" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html#como-dibujar-varias-densidades-en-una-misma-figura"><i class="fa fa-check"></i><b>7.4</b> ¿Cómo dibujar varias densidades en una misma figura?</a></li>
<li class="chapter" data-level="7.5" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html#como-dibujar-varias-densidades-transparentes-en-una-misma-figura"><i class="fa fa-check"></i><b>7.5</b> ¿Cómo dibujar varias densidades transparentes en una misma figura?</a></li>
<li class="chapter" data-level="7.6" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html#como-incluir-una-rejilla-a-una-figura-en-ciertos-puntos"><i class="fa fa-check"></i><b>7.6</b> ¿Cómo incluir una rejilla a una figura en ciertos puntos? </a></li>
<li class="chapter" data-level="7.7" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html#como-incluir-en-un-grafico-valores-en-forma-automatica"><i class="fa fa-check"></i><b>7.7</b> ¿Cómo incluir en un gráfico valores en forma automática?</a></li>
<li class="chapter" data-level="7.8" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html#como-incluir-en-un-grafico-varios-valores-en-forma-automatica"><i class="fa fa-check"></i><b>7.8</b> ¿Cómo incluir en un gráfico varios valores en forma automática?</a></li>
<li class="chapter" data-level="7.9" data-path="respuestas-a-preguntas-frecuentes.html"><a href="respuestas-a-preguntas-frecuentes.html#como-incluir-colores-dependiendo-de-los-valores-de-una-variable-cualitativa"><i class="fa fa-check"></i><b>7.9</b> ¿Cómo incluir colores dependiendo de los valores de una variable cualitativa?</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="extras.html"><a href="extras.html"><i class="fa fa-check"></i><b>8</b> Extras</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Gráficos con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="graficos-para-variables-cualitativas" class="section level1">
<h1><span class="header-section-number">4</span> Gráficos para variables cualitativas</h1>
<p>En este capítulo se presentan funciones para la creación de gráficos para variables cualitativas.</p>
<div id="funcion-barplot" class="section level2">
<h2><span class="header-section-number">4.1</span> Función <code>barplot</code>  </h2>
<p>Los gráficos de barras son útiles para representar las frecuencias absolutas o relativas asociadas a los niveles de una variable cualitativa y la función <code>barplot</code> se usa para obtener un gráfico de barras. La estructura de la función <code>barplot</code> con los argumentos más comunes de uso se muestra a continuación.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(height, beside, horiz)</code></pre>
<p>Los argumentos de la función <code>barplot</code> son:</p>
<ul>
<li><code>height</code>: vector o matriz con la información de las frecuencias absolutas o relativas.</li>
<li><code>beside</code>: valor lógico para indicar si las barras deben estar al lado cuando la información ingresada es una matriz.</li>
<li><code>horiz</code>: valor lógico para indicar si el diagrama de barras debe ser horizontal, por defecto es <code>FALSE</code>.</li>
</ul>
<p>La función <code>barplot</code> tiene otros parámetros que pueden ser consultados en la ayuda de la función por medio de la instrucción <code>?barplot</code>.</p>
<div id="ejemplo-28" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Suponga que queremos construir un diagrama de barras para las frecuencias relativas de la variable estrato socioeconómico del apartamento de la base de datos sobre apartamentos usados en Medellín.</p>
<p>A continuación se muestra el código necesario para cargar la base de datos <code>aptos2015</code>. Antes de construir el diagrama de barras solicitado es necesario construir la tabla de frecuencias para la variable estrato, para esto se usa la función <code>table</code> y los resultados se almacenan en el objeto <code>tabla1</code> que contiene las frecuencias <strong>absolutas</strong>. Para obtener las frecuencias <strong>relativas</strong> se usa luego la función <code>prop.table</code> sobre el objeto <code>tabla1</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">url &lt;-<span class="st"> &#39;https://tinyurl.com/hwhb769&#39;</span>
datos &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="dt">file=</span>url, <span class="dt">header=</span>T)
tabla1 &lt;-<span class="st"> </span><span class="kw">table</span>(datos<span class="op">$</span>estrato)
tabla1 &lt;-<span class="st"> </span><span class="kw">prop.table</span>(tabla1)
tabla1</code></pre>
<pre><code>## 
##          2          3          4          5          6 
## 0.01152738 0.23198847 0.19884726 0.20893372 0.34870317</code></pre>
<p>Una vez se tiene el objeto con la información de las frecuencias relativas se puede dibujar el diagrama de barras usando el siguiente código.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(tabla1, <span class="dt">xlab=</span><span class="st">&#39;Estrato socioeconómico&#39;,</span>
<span class="st">        ylab=&#39;</span>Frecuencia relativa<span class="st">&#39;, las=1)</span></code></pre>
<div class="figure"><span id="fig:barra1"></span>
<img src="Graficos_con_R_files/figure-html/barra1-1.png" alt="Diagrama de barras para el estrato socioeconómico de los apartamentos usados." width="672" />
<p class="caption">
Figure 4.1: Diagrama de barras para el estrato socioeconómico de los apartamentos usados.
</p>
</div>
<p>En la Figura <a href="graficos-para-variables-cualitativas.html#fig:barra1">4.1</a> se presenta el diagrama de barras solicitado. Se observa que hay pocos apartamentos (1.15%) pertenecientes al estrato dos, los estratos tres, cuatro y cinco aportan porcentajes similares a la base de datos y que el estrato 6 es el que más apartamentos aporta a la base de datos, 34.87%.</p>
<p>Algunas veces se acostumbra a colocar las frecuencias relativas sobre la parte superior de las barras para facilitar la lectura. A continuación se presenta el código para replicar la Figura <a href="graficos-para-variables-cualitativas.html#fig:barra1">4.1</a> con las frecuencias relativas. Lo primero que se hace es dibujar el diagrama de barras y almacenar la información de él en el objeto <code>xx</code> para luego poder usar la ubicación de cada una de las barras. Note que se agregó también <code>ylim=c(0, 0.45)</code> para conseguir una ampliación del eje vertical, esto para lograr que se vea el número sobre la barra del estrato 6. Luego se usa la función <code>text</code> para incluir un texto en las coordenadas <code>x=xx</code> y <code>y=tabla1</code>, el parámetro <code>pos=3</code> coloca el texto en la parte superior de las coordenadas y el parámetro <code>label</code> sirve para indicar lo que se desea escribir en las coordenadas indicadas, en este caso son las frecuencias relativas almacenadas en <code>tabla1</code>.</p>
<pre class="sourceCode r"><code class="sourceCode r">xx &lt;-<span class="st"> </span><span class="kw">barplot</span>(tabla1, <span class="dt">ylim=</span><span class="kw">c</span>(<span class="dv">0</span>, <span class="fl">0.45</span>), <span class="dt">col=</span><span class="kw">gray</span>(<span class="fl">0.9</span>),
              <span class="dt">xlab=</span><span class="st">&#39;Estrato socioeconómico&#39;,</span>
<span class="st">              ylab=&#39;</span>Frecuencia relativa<span class="st">&#39;, las=1)</span>

<span class="st">text(x=xx, y=tabla1, pos=3, cex=0.8, col=&quot;red&quot;,</span>
<span class="st">     label=round(tabla1, 4))</span></code></pre>
<div class="figure"><span id="fig:barra2"></span>
<img src="Graficos_con_R_files/figure-html/barra2-1.png" alt="Diagrama de barras para el estrato socioeconómico de los apartamentos usados con las frecuencias relativas sobre las barras." width="672" />
<p class="caption">
Figure 4.2: Diagrama de barras para el estrato socioeconómico de los apartamentos usados con las frecuencias relativas sobre las barras.
</p>
</div>
<p>En la Figura <a href="graficos-para-variables-cualitativas.html#fig:barra2">4.2</a> se muestra el diagrama de barras modificado. Note que si no se hubiese usado <code>ylim=c(0, 0.45)</code> al dibujar el diagrama, la marca sobre la última barra no se podría ver.</p>
</div>
<div id="ejemplo-29" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Suponga que queremos construir un diagrama de barras para comparar la variable presencia de parqueadero con el estrato socioeconómico en la base de datos sobre apartamentos usados en Medellín.</p>
<p>La función <code>barplot</code> también puede ser usada para representar una tabla de frecuencia con dos variables. Para obtener la tabla de frecuencia para relacionar parqueadero con estrato se usa el siguiente código.</p>
<pre class="sourceCode r"><code class="sourceCode r">tabla2 &lt;-<span class="st"> </span><span class="kw">table</span>(datos<span class="op">$</span>parqueadero, datos<span class="op">$</span>estrato)
tabla2</code></pre>
<pre><code>##     
##        2   3   4   5   6
##   no   5  88  24   8   1
##   si   3  73 114 137 241</code></pre>
<p>El anterior resultado es la tabla de contingencia entre las variables parqueadero y estrato, de esta tabla vemos que para estratos superiores el número de apartamentos que si tienen parqueadero es mayor que los apartamentos sin parqueadero. La tabla anterior se puede representar gráficamente usando el siguiente código.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(tabla2)</code></pre>
<div class="figure"><span id="fig:barra3"></span>
<img src="Graficos_con_R_files/figure-html/barra3-1.png" alt="Diagrama I de barras la relación entre parqueadero y estrato." width="672" />
<p class="caption">
Figure 4.3: Diagrama I de barras la relación entre parqueadero y estrato.
</p>
</div>
<p>En la Figura <a href="graficos-para-variables-cualitativas.html#fig:barra3">4.3</a> se muestra el gráfico de barras sin editar, el color negro representa la frecuencia de los apartamentos sin parqueadero (no) y el color gris representa los apartamentos con parqueadero (si), las barras están una encima de la otra y la comparación no es tan clara como debería. Para mejorar la comparación se usa el parámetro <code>besides=TRUE</code>, a continuación el código utilizado.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(tabla2, <span class="dt">beside=</span><span class="ot">TRUE</span>)</code></pre>
<div class="figure"><span id="fig:barra4"></span>
<img src="Graficos_con_R_files/figure-html/barra4-1.png" alt="Diagrama II de barras la relación entre parqueadero y estrato." width="672" />
<p class="caption">
Figure 4.4: Diagrama II de barras la relación entre parqueadero y estrato.
</p>
</div>
<p>En la Figura <a href="graficos-para-variables-cualitativas.html#fig:barra4">4.4</a> está el gráfico de barras obtenido agregando <code>besides=TRUE</code> para que las barras se ubiquen una junto a la otra. Este gráfico se puede mejorar aún más colocando una leyenda para identificar las barras, nombrando los ejes y usando otros colores, a continuación el código utilizado.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(tabla2, <span class="dt">beside =</span> <span class="ot">TRUE</span>, <span class="dt">las=</span><span class="dv">1</span>, 
        <span class="dt">xlab=</span><span class="st">&#39;Estrato&#39;</span>, <span class="dt">ylab=</span><span class="st">&#39;Frecuencia&#39;</span>,
        <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;mistyrose&quot;</span>),
        <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">250</span>))
<span class="kw">legend</span>(<span class="st">&#39;topleft&#39;</span>, <span class="dt">legend=</span><span class="kw">rownames</span>(tabla2), <span class="dt">bty=</span><span class="st">&#39;n&#39;</span>,
       <span class="dt">fill=</span><span class="kw">c</span>(<span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;mistyrose&quot;</span>))</code></pre>
<div class="figure"><span id="fig:barra5"></span>
<img src="Graficos_con_R_files/figure-html/barra5-1.png" alt="Relación entre la presencia de parqueadero y el estrato socioeconómico." width="672" />
<p class="caption">
Figure 4.5: Relación entre la presencia de parqueadero y el estrato socioeconómico.
</p>
</div>
<p>En la Figura <a href="graficos-para-variables-cualitativas.html#fig:barra5">4.5</a> se observa el gráfico de barras solicitado, se observa claramente que en los estratos 4, 5 y 6 predominan los aparatamentos con parqueadero.</p>
<p>Es posible construir una tabla de contingencia de frecuencia relativa para ver cómo es el comportamiento de tener o no parquedadero dentro de cada estrato, el siguiente código construye la <code>tabla3</code> con la información necesaria. La función <code>prop.table</code> permite obtener la tabla de frecuencias <strong>relativas</strong> a partir de una tabla de frecuencias absolutas, el parámetro <code>margin</code> sirve para indicar si las frecuencias <strong>relativas</strong> se deben obtener por fila (<code>margin=1</code>) o por columnas (<code>margin=2</code>).</p>
<pre class="sourceCode r"><code class="sourceCode r">tabla3 &lt;-<span class="st"> </span><span class="kw">prop.table</span>(tabla2, <span class="dt">margin=</span><span class="dv">2</span>)
tabla3</code></pre>
<pre><code>##     
##                2           3           4           5           6
##   no 0.625000000 0.546583851 0.173913043 0.055172414 0.004132231
##   si 0.375000000 0.453416149 0.826086957 0.944827586 0.995867769</code></pre>
<p>De la anterior tabla se ve que el porcentaje de apartamentos con parqueadero supera enormemente el los apartamentos sin parqueadero para los estratos 6, 5 y 4. El código para generar un gráfico asociado a la <code>tabla3</code> se muestra a continuación.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">barplot</span>(tabla3, 
        <span class="dt">beside =</span> <span class="ot">TRUE</span>, <span class="dt">las=</span><span class="dv">1</span>, 
        <span class="dt">xlab=</span><span class="st">&#39;Estrato&#39;</span>, <span class="dt">ylab=</span><span class="st">&#39;Frecuencia relativa&#39;</span>,
        <span class="dt">col =</span> <span class="kw">c</span>(<span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;mistyrose&quot;</span>),
        <span class="dt">ylim =</span> <span class="kw">c</span>(<span class="dv">0</span>, <span class="dv">1</span>))
<span class="kw">legend</span>(<span class="st">&#39;topleft&#39;</span>, <span class="dt">legend=</span><span class="kw">rownames</span>(tabla2), <span class="dt">bty=</span><span class="st">&#39;n&#39;</span>,
       <span class="dt">fill=</span><span class="kw">c</span>(<span class="st">&quot;lightblue&quot;</span>, <span class="st">&quot;mistyrose&quot;</span>))</code></pre>
<div class="figure"><span id="fig:barra6"></span>
<img src="Graficos_con_R_files/figure-html/barra6-1.png" alt="Relación entre la presencia de parqueadero y el estrato socioeconómico." width="672" />
<p class="caption">
Figure 4.6: Relación entre la presencia de parqueadero y el estrato socioeconómico.
</p>
</div>
<p>¿Cuáles son las ventajas y/o desventajas de las figuras <a href="graficos-para-variables-cualitativas.html#fig:barra5">4.5</a> y <a href="graficos-para-variables-cualitativas.html#fig:barra6">4.6</a> al ser presentadas en un informe?</p>
</div>
</div>
<div id="funcion-pie" class="section level2">
<h2><span class="header-section-number">4.2</span> Función <code>pie</code>  </h2>
<p>En  es posible construir gráficos de pastel para representar una tabla de frecuencia relativa o absoluta, sin embargo este tipo de gráficos no es recomendable y en la ayuda de la función se hace la siguiente advertencia:</p>

<div class="rmdwarning">
Pie charts are a very bad way of displaying information. The eye is good at judging linear measures and bad at judging relative areas. A bar chart or dot chart is a preferable way of displaying this type of data.
</div>

<p>La estructura de la función <code>pie</code> con los argumentos más comunes de uso se muestra a continuación.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">pie</span>(x, labels)</code></pre>
<p>Los argumentos de la función <code>pie</code> son:</p>
<ul>
<li><code>x</code>: vector con elementos no negativos que representan las frecuencias de los niveles de la variable cualitativa.</li>
<li><code>labels</code>: vector con los nombres a colocar en cada parte del pastel, por defecto se usan los nombres del vector <code>x</code>.</li>
</ul>
<div id="ejemplo-30" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Dibujar un gráfico de pastel para las frecuencias relativas de la variable estrato socioeconómico del apartamento de la base de datos sobre apartamentos usados en Medellín.</p>
<p>La <code>tabla1</code> construída en el primer ejemplo de <code>barplot</code> se utiliza para construir el gráfico solicitado. Abajo el código necesario para construir el gráfico.</p>
<pre class="sourceCode r"><code class="sourceCode r">nombres &lt;-<span class="st"> </span><span class="kw">paste</span>(<span class="st">&#39;Estrato &#39;</span>, <span class="dv">2</span><span class="op">:</span><span class="dv">6</span>)
<span class="kw">pie</span>(<span class="dt">x=</span>tabla1, <span class="dt">labels=</span>nombres, 
    <span class="dt">main=</span><span class="st">&#39;Gráfico de pastel NO recomendado!!!&#39;</span>)</code></pre>
<div class="figure"><span id="fig:pie"></span>
<img src="Graficos_con_R_files/figure-html/pie-1.png" alt="Gráfico de pastel para las frecuencias relativas del estrato socioeconómico." width="672" />
<p class="caption">
Figure 4.7: Gráfico de pastel para las frecuencias relativas del estrato socioeconómico.
</p>
</div>
<p>La Figura <a href="graficos-para-variables-cualitativas.html#fig:pie">4.7</a> presenta el gráfico de pastel construído con la instrucción anterior.</p>
</div>
</div>
<div id="funcion-dotchart" class="section level2">
<h2><span class="header-section-number">4.3</span> Función <code>dotchart</code>  </h2>
<p>Los gráficos de puntos son útiles para representar tablas de frecuencia (de 1 o 2 vías) o tablas de resumen en relación a una o dos variables. La estructura de la función <code>dotchart</code> se muestra a continuación.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dotchart</span>(x, <span class="dt">labels=</span><span class="ot">NULL</span>, <span class="dt">groups=</span><span class="ot">NULL</span>, <span class="dt">gdata=</span><span class="ot">NULL</span>,
         pt.cex, pch, color, lcolor, ...)</code></pre>
<p>Los argumentos de la función <code>dotchart</code> son:</p>
<ul>
<li><code>x</code>: vector o matriz con la información de las frecuencias o medida de resumen a representar. Si <code>x</code> es una matriz las columnas representarán agrupaciones.</li>
<li><code>labels</code>: vector con los nombres a usar para los puntos, por defecto toma los nombres de las filas de la matriz <code>x</code>.</li>
<li><code>groups</code>: vector con los nombres a usar para los grupos, por defecto toma los nombres de las columnas de la matriz <code>x</code>.</li>
<li><code>cex</code>: tamaño de los nombres a mostrar en los ejes.</li>
<li><code>pt.cex</code>: tamaño del punto.</li>
<li><code>pch</code>: tipo de punto a usar, las diferentes opciones para <code>pch</code> están disponibles en la Figura <a href="funciones-auxiliares.html#fig:point1">6.11</a>.</li>
<li><code>color</code>: tipo de color usar para los puntos.</li>
<li><code>lcolor</code>: color para la línea asociada a cada punto.</li>
<li><code>...</code>: otros parámetros gráficos que pueden ser pasados como argumentos.</li>
</ul>
<div id="ejemplo-31" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Suponga que queremos explorar el rendimiento de del combustible (<code>mpg</code>) para los 32 autos de la base de datos <code>mtcars</code> usando un diagrama de puntos.</p>
<p>A continuación se muestra el código necesario para crear el gráfico de puntos deseado.</p>
<pre class="sourceCode r"><code class="sourceCode r">mtcars &lt;-<span class="st"> </span>mtcars[<span class="kw">order</span>(mtcars<span class="op">$</span>mpg), ]  <span class="co"># Para re-ordenar la base</span>
<span class="kw">dotchart</span>(mtcars<span class="op">$</span>mpg, <span class="dt">labels=</span><span class="kw">row.names</span>(mtcars), 
         <span class="dt">cex=</span><span class="fl">0.6</span>, <span class="dt">xlab=</span><span class="st">&quot;mpg&quot;</span>)</code></pre>
<div class="figure"><span id="fig:dotchart1"></span>
<img src="Graficos_con_R_files/figure-html/dotchart1-1.png" alt="Gráfico de puntos para el rendimiento de combustible (`mpg`) en la base de datos `mtcars`." width="576" />
<p class="caption">
Figure 4.8: Gráfico de puntos para el rendimiento de combustible (<code>mpg</code>) en la base de datos <code>mtcars</code>.
</p>
</div>
<p>En la Figura <a href="graficos-para-variables-cualitativas.html#fig:dotchart1">4.8</a> se tiene el gráfico de puntos para la variable <code>mpg</code>, de esta figura se observa fácilmente que el Toyota Corolla tiene el mayor rendimiento de combustible y que el Cadillac Fleetwood el menor.</p>
</div>
<div id="ejemplo-32" class="section level3 unnumbered">
<h3>Ejemplo</h3>
<p>Suponga que se tiene una tabla de contingencia con la información del número de hombres y mujeres que sufren de una enfermedad rara en cuatro ciudades importantes del mundo, a continuación la matriz <code>x</code> con la información recolectada.</p>
<pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">4</span>, <span class="dv">6</span>, <span class="dv">30</span>, <span class="dv">18</span>, <span class="dv">7</span>, <span class="dv">13</span>, <span class="dv">35</span>, <span class="dv">20</span>),
            <span class="dt">ncol=</span><span class="dv">4</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)
<span class="kw">colnames</span>(x) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Madrid&#39;</span>, <span class="st">&#39;Londres&#39;</span>, <span class="st">&#39;Paris&#39;</span>, <span class="st">&#39;Miami&#39;</span>)
<span class="kw">rownames</span>(x) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&#39;Hombre&#39;</span>, <span class="st">&#39;Mujer&#39;</span>)
x</code></pre>
<pre><code>##        Madrid Londres Paris Miami
## Hombre      4       6    30    18
## Mujer       7      13    35    20</code></pre>
<p>En la salida anterior se presenta la matriz <code>x</code>, de esta matriz se observa que en Madrid hay 11 personas, 4 hombres y 7 mujeres que sufren de la enfermedad, las demás columnas se interpretan de forma similar.</p>
<p>Para construir un gráfico de puntos con el objetivo de presentar la información de la matriz <code>x</code> se utiliza el código mostrado abajo. En la Figura <a href="graficos-para-variables-cualitativas.html#fig:dotchart2">4.9</a> se presenta el gráfico de puntos obtenido y de esta figura se nota claramente que en París es donde hay más personas que sufren de la enfermedad.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dotchart</span>(<span class="dt">x=</span>x)</code></pre>
<div class="figure"><span id="fig:dotchart2"></span>
<img src="Graficos_con_R_files/figure-html/dotchart2-1.png" alt="Gráfico de puntos para una tabla de contingencia de 2 variables." width="576" />
<p class="caption">
Figure 4.9: Gráfico de puntos para una tabla de contingencia de 2 variables.
</p>
</div>
<p>El gráfico de puntos presentado en la Figura <a href="graficos-para-variables-cualitativas.html#fig:dotchart2">4.9</a> se puede mejorar usando los otros argumentos disponibles en la función <code>dotchart</code>, a continuación el código y en la Figura <a href="graficos-para-variables-cualitativas.html#fig:dotchart3">4.10</a> el resultado.</p>
<pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dotchart</span>(<span class="dt">x=</span>x,
         <span class="dt">pt.cex=</span><span class="dv">2</span>, <span class="dt">pch=</span><span class="kw">c</span>(<span class="dv">8</span>, <span class="dv">21</span>), <span class="dt">color=</span><span class="kw">c</span>(<span class="st">&#39;blue&#39;</span>, <span class="st">&#39;red&#39;</span>),
         <span class="dt">lcolor=</span><span class="st">&#39;black&#39;</span>, 
         <span class="dt">xlab=</span><span class="st">&#39;Número de personas&#39;</span>)</code></pre>
<div class="figure"><span id="fig:dotchart3"></span>
<img src="Graficos_con_R_files/figure-html/dotchart3-1.png" alt="Gráfico de puntos mejorado para una tabla de contingencia de 2 variables." width="576" />
<p class="caption">
Figure 4.10: Gráfico de puntos mejorado para una tabla de contingencia de 2 variables.
</p>
</div>
</div>
</div>
<div id="ejercicios" class="section level2 unnumbered">
<h2>EJERCICIOS</h2>
<p>Use funciones o procedimientos (varias líneas) de  para responder cada una de las siguientes preguntas.</p>
<p>Todas las preguntas siguientes están relacionadas con la base de datos sobre <a href="https://raw.githubusercontent.com/fhernanb/datos/master/aptos2015">apartamentos</a> usados en la ciudad de Medellín.</p>
<ol style="list-style-type: decimal">
<li>Construya un diagrama de barras para representar las frecuencias ABSOLUTAS de la variable ubicación.</li>
<li>Vuelva a construir el mismo diagrama de barras anterior pero de forma horizontal y agregando números de color azul para indicar las frecuencias.</li>
<li>Construya una tabla de dos vías para las variables ubicación y parqueadero.</li>
<li>Construya una tabla de frecuencias relativas para ver cómo se comporta la variable parqueadero dentro de cada ubicación.</li>
<li>Dibuje un diagrama de barras para la tabla de frecuencias del punto anterior.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="dos-cuanti.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="funcion-par.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/fhernanb/Graficos-con-R/edit/master/04_graphs_cuali.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
